'use client'
import './globals.css'
import { poppins } from './fonts/font'
import { VacancyProvider } from './context';
import { Footer, Navbar } from '@/components';
import { useWindowSize } from '@/utils/window_size';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  const size = useWindowSize();

  return (
    <html lang="en">
      <body className={`${poppins.variable}`}>
        <VacancyProvider>
          {
            size.width >= 600 ?
              <Navbar /> : <p>mobile size</p>
          }
          <main>
            {children}
          </main>
          {
            size.width >= 600 ? <Footer /> : <p>mobile size</p>
          }
        </VacancyProvider>
      </body>
    </html>
  )
}
